---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dnsutils
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - tail
      - -f
      - /dev/null
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
